// react-sub-app/src/App.jsx
import React, { useState, useEffect } from 'react'
import { BrowserRouter, Routes, Route, Link, useLocation } from 'react-router-dom'
import Home from './views/Home'
import About from './views/About'
import Products from './views/Products'
import Contact from './views/Contact'
import Dashboard from './views/Dashboard'
import './App.css'

function App({ routerBase }) {
  const [isDark, setIsDark] = useState(false)

  // 根据是否在 qiankun 环境中动态设置 basename
  const isQiankun = window.__POWERED_BY_QIANKUN__
  const basename = isQiankun ? (routerBase || '/react') : '/'

  // 检查主题
  useEffect(() => {
    const checkTheme = () => {
      const theme = document.documentElement.getAttribute('data-theme')
      setIsDark(theme === 'dark')
    }

    checkTheme()

    // 监听主题变化
    const observer = new MutationObserver(() => {
      checkTheme()
    })

    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['data-theme']
    })

    return () => observer.disconnect()
  }, [])

  return (
    <div className={`sub-app ${isDark ? 'dark-mode' : ''}`}>
      <div className="sub-app-header">
        <h2>React 子应用</h2>
        <p>这是一个使用 vite-plugin-qiankun 接入的 React 子应用</p>
      </div>
      <BrowserRouter basename={basename}>
        <NavContent />
      </BrowserRouter>
    </div>
  )
}

// 导航内容组件，需要在 BrowserRouter 内部使用 useLocation
function NavContent() {
  const location = useLocation()


  // 导航链接组件，用于高亮当前路由
  function NavLink({ to, children }) {
    const isActive = location.pathname === to || location.pathname === `${to}`

    return (
      <Link
        to={to}
        className={`nav-item ${isActive ? 'active' : ''}`}
      >
        {children}
      </Link>
    )
  }

  return (
    <div className="sub-app-content">
      <nav className="sub-nav">
        <NavLink to="/home">首页</NavLink>
        <NavLink to="/dashboard">数据看板</NavLink>
        <NavLink to="/products">产品列表</NavLink>
        <NavLink to="/about">关于</NavLink>
        <NavLink to="/contact">联系我们</NavLink>
      </nav>
      <div className="sub-content">
        <Routes>
          <Route path="/home" element={<Home />} />
          <Route path="/dashboard" element={<Dashboard />} />
          <Route path="/products" element={<Products />} />
          <Route path="/about" element={<About />} />
          <Route path="/contact" element={<Contact />} />
          <Route path="/" element={<Home />} />
          <Route path="*" element={
            <div style={{ padding: '2rem', textAlign: 'center' }}>
              <h3>404 - 页面未找到</h3>
              <p>当前路径: {location.pathname}</p>
              <p>请检查路由配置</p>
            </div>
          } />
        </Routes>
      </div>
    </div>
  )
}

export default App

// vue-sub-app/src/App.vue
<template>
  <div class="sub-app" :class="{ 'dark-mode': isDark }">
    <div class="sub-app-header">
      <h2>Vue 子应用</h2>
      <p>这是一个可以接入 qiankun 主应用的子应用</p>
    </div>
    <div class="sub-app-content">
      <nav class="sub-nav">
        <router-link to="/home" class="nav-item">首页</router-link>
        <router-link to="/about" class="nav-item">关于</router-link>
      </nav>
      <div class="sub-content">
        <router-view />
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, watch } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const isDark = ref(false)

// 检查主题
const checkTheme = () => {
  const theme = document.documentElement.getAttribute('data-theme')
  isDark.value = theme === 'dark'
}

// 监听主题变化
const observer = new MutationObserver(() => {
  checkTheme()
})

onMounted(() => {
  checkTheme()
  // 监听 data-theme 属性变化
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ['data-theme']
  })
})
</script>

<style scoped>
.sub-app {
  min-height: 100vh;
  padding: 2rem;
  background-color: #ffffff;
  color: #333;
  transition: background-color 0.3s, color 0.3s;
}

.sub-app.dark-mode {
  background-color: #1a1a1a;
  color: #e0e0e0;
}

.sub-app-header {
  margin-bottom: 2rem;
  padding-bottom: 1rem;
  border-bottom: 2px solid #e0e0e0;
}

.sub-app.dark-mode .sub-app-header {
  border-bottom-color: #444;
}

.sub-app-header h2 {
  margin: 0 0 0.5rem 0;
  color: #667eea;
}

.sub-app.dark-mode .sub-app-header h2 {
  color: #8b9aff;
}

.sub-app-content {
  display: flex;
  gap: 2rem;
}

.sub-nav {
  min-width: 200px;
  padding: 1rem;
  background: #f5f5f5;
  border-radius: 8px;
  height: fit-content;
}

.sub-app.dark-mode .sub-nav {
  background: #2a2a2a;
}

.nav-item {
  display: block;
  padding: 0.75rem 1rem;
  margin-bottom: 0.5rem;
  color: #333;
  text-decoration: none;
  border-radius: 4px;
  transition: all 0.3s;
}

.sub-app.dark-mode .nav-item {
  color: #e0e0e0;
}

.nav-item:hover {
  background-color: #e0e0e0;
}

.sub-app.dark-mode .nav-item:hover {
  background-color: #3a3a3a;
}

.nav-item.router-link-active {
  background-color: #667eea;
  color: white;
}

.sub-app.dark-mode .nav-item.router-link-active {
  background-color: #8b9aff;
  color: #1a1a1a;
}

.sub-content {
  flex: 1;
  padding: 1.5rem;
  background: #ffffff;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.sub-app.dark-mode .sub-content {
  background: #2a2a2a;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
}
</style>
